### ISSUE TITLE
Panic recovery

### ISSUE THREAD

**Issue by c4s4** [long2ice/swagin#12]
When a panic is raised in an handler, server doesn't catch and manage this panic to return a status 500 (Internal Server Error) response. Instead, it returns nothing to the client. This is demonstrated with this code:

```go
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/long2ice/swagin"
	"github.com/long2ice/swagin/router"
	"github.com/long2ice/swagin/swagger"
)

func main() {
	app := swagin.New(swagger.New("SwaGin", "Swagger + Gin = SwaGin", "0.1.0"))
	app.GET("/", test)
	if err := app.Run(); err != nil {
		panic(err)
	}
}

var test = router.New(
	&Test{},
	router.Summary("Test query"),
	router.Description("Test query model"),
)

type Test struct{}

func (t *Test) Handler(ctx *gin.Context) {
	panic("test")
}
```

This can be fixed adding a recovery handler to the Gin engine. This handler will trap the panic and return appropriate response to client.

**Comment by long2ice** [comment]
Just use `app.Use(recovery())`
