### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by c4s4** [long2ice/swagin#15]
In following example:

```go
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/long2ice/swagin"
	"github.com/long2ice/swagin/router"
	"github.com/long2ice/swagin/swagger"
)

func main() {
	app := swagin.New(swagger.New("SwaGin", "Swagger + Gin = SwaGin", "0.1.0"))
	app.GET("/", test)
	if err := app.Run(); err != nil {
		panic(err)
	}
}

var test = router.New(
	&Test{},
	router.Summary("Test query"),
	router.Description("Test query model"),
)

type Test struct{
	Authorization string `header:"authorization" binding:"required" json:"authorization" default:"authorization"`
	Token string `header:"token" binding:"required" json:"token" default:"token"`
}

func (t *Test) Handler(ctx *gin.Context) {
	println(">>>>>>>>>> authorization:", t.Authorization)
	println(">>>>>>>>>> token:", t.Token)
}
```

I require two headers in request (_Token_ and _Authorization_). They are both listed in documentation (at URL _/docs_) and I can set them to perform request. But validation fails for header _Authorization_ which is missing, while _Token_ is sent and received. Furthermore, in CURL example request _Authorization_ header is missing while _Token_ is set.

In my opinion, both headers should be sent. Why is _Authorization_ missing?

This seems to be a collision with authorization bechanism in SwaGin, as it works fine with other headers.

**Comment by long2ice** [comment]
Latest code is ok
