### ISSUE TITLE
hot reload option

### ISSUE THREAD

**Issue by gsbecerrag** [long2ice/swagin#4]
Quick question, is there a way to enable a "hot reload" kind of option? I'd read that `gin run main.go --all` does that trick when using the gin package directly, but I was not able to get that to work inside `swagin`

I'm very new at Go and this package is helping me a lot moving from python (FastAPI) to Go, great work!!!

**Comment by long2ice** [comment]
`SwaGin` just inherit `gin.Engine`, but I don't use that before

**Comment by gsbecerrag** [comment]
Ok, I see. I tried using another package called `fresh` to restart the app when a change is made and worked as intended. If anyone needs that kind of functionality here's the info:

[https://github.com/gravityblast/fresh](url)
